// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3853.ProgTrainingRobot.subsystems;

import org.usfirst.frc3853.ProgTrainingRobot.RobotMap;
import org.usfirst.frc3853.ProgTrainingRobot.commands.*;
import edu.wpi.first.wpilibj.Joystick;


import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class Drive extends Subsystem {
  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftSpeedController = RobotMap.driveLeftSpeedController;
    private final SpeedController rightSpeedController = RobotMap.driveRightSpeedController;
    private final RobotDrive robotDrive21 = RobotMap.driveRobotDrive21;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
  

  // Put methods for controlling this subsystem
  // here. Call these from Commands.
  public void doTeleop(Joystick stick) {
    SmartDashboard.putString("doTeleop", "RanIt");
    robotDrive21.arcadeDrive(stick,false);
  }

  public void driveForward(double speed) {
    // speed is 0 stopped to 1 full speed
    speed = Math.abs(speed);
    if(speed > 1){
      speed = 1;
      }
    robotDrive21.arcadeDrive(-speed, 0);
  }

  public void driveBackward(double speed) {
    // speed is 0 stopped to 1 full speed
    speed = Math.abs(speed);
    if(speed > 1){
      speed = 1;
      }
    robotDrive21.arcadeDrive(speed, 0);
  }

  public void stop() {
    robotDrive21.arcadeDrive(0, 0);
  }

  public void initDefaultCommand() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveTeleop());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // Set the default command for a subsystem here.
    // setDefaultCommand(new MySpecialCommand());
  }
}
